# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "jira4r"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Walding"]
  s.date = "2012-06-12"
  s.description = "JIRA SOAP binding library for Ruby"
  s.email = "bwalding@codehaus.org"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "NOTICE",
    "README.md",
    "Rakefile",
    "VERSION",
    "examples/example-utils.rb",
    "examples/subtract-members",
    "jira4r.gemspec",
    "lib/jira4r/.DS_Store",
    "lib/jira4r/jira4r.rb",
    "lib/jira4r/jira_tool.rb",
    "lib/jira4r/v2/.DS_Store",
    "lib/jira4r/v2/JiraSoapServiceDriver.rb",
    "lib/jira4r/v2/jiraService.rb",
    "lib/jira4r/v2/jiraServiceMappingRegistry.rb",
    "lib/jiraService.rb",
    "lib/jiraServiceMappingRegistry.rb",
    "spec/.gitignore",
    "spec/jira4r_spec.rb",
    "spec/spec_helper.rb",
    "wsdl/jirasoapservice-v2.wsdl"
  ]
  s.homepage = "https://xircles.rubyhaus.org/projects/jira4r"
  s.licenses = ["ASLv2"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "JIRA SOAP binding library for Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<soap4r-ruby1.9>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<soap4r-ruby1.9>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<soap4r-ruby1.9>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

